# The version of the Docker Compose file format
version: '3'

# The services that make up your app are defined in this section
services:

  # Each service is built from the Dockerfile in the specified directory
  
  # The Manager service
  manager:
    build: ./manager   # build the service using the Dockerfile in the manager directory
    ports:
      - "80:80"     # map TCP port 80 on the host to port 80 in the container
      - "443:443"     # map TCP port 80 on the host to port 80 in the container
    depends_on:
      - editor          # this service depends on the editor service

  # The Editor service
  editor:
    build: ./editor    # build the service using the Dockerfile in the editor directory
    ports:
      - "8080:80"      # map TCP port 5001 on the host to port 80 in the container
    depends_on:
      - researcher     # this service depends on the researcher service

  # The Researcher service
  researcher:
    build: ./researcher  # build the service using the Dockerfile in the researcher directory
    ports:
      - "5002:80"       # map TCP port 5002 on the host to port 80 in the container
    volumes:
      - ./researcher:/app  # mount the researcher directory on the host to /app in the container

# Note: The Tools service is not included here as it is built as a Python wheel and included in the other services.
